spring:
  application:
    name: transfers-gateway

server:
  port: 8888

transfers-gateway:
  ratio: 0.6
  routes:
    - route:
        name: default
        host: localhost
        port: 8090
        url: transfers/
    - route:
        name: experimental
        host: localhost
        port: 9090
        url: transfers/
